name: moves_final_project
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  google_fonts: ^8.0.2

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  dio: ^5.9.1
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  pretty_dio_logger: ^1.4.0
  loader_overlay: ^5.0.0
  cached_network_image: ^3.4.1
  injectable: ^2.7.1+4
  get_it: ^9.2.1
  provider: ^6.1.5+1
  carousel_slider: ^5.1.2
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.4
  introduction_screen: ^4.0.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  injectable_generator: ^2.9.0
  build_runner: ^2.11.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/


